#!/bin/sh

choices="laptop\nlaptopdual\nHDMI\nManual selection"

chosen=$(echo -e "$choices" | dmenu -i)

case "$chosen" in
	laptopdual) xrandr --output eDP-1 --auto --output HDMI-2 --auto --left-of eDP-1 ;;
	laptop) xrandr --output eDP-1 --auto --output HDMI-2 --off ;;
	DP) xrandr --output DP-1 --auto --output eDP-1 --off ;;
	HDMI) xrandr --output HDMI-2 --auto --output eDP-1 --off ;;
	"Manual selection") arandr ;;
esac

# Relaunch polybar if there was a selection.
[ "$chosen" == "" ] || polybar_launch
