#!/bin/bash

## Defaults
USER="thomasmeulendijks"
REPO="${PWD##*/}" # Current directry name

while getopts u:r: option
do
	case "${option}"
		in
		u) USER=${OPTARG};;
		r) REPO=${OPTARG};;
	esac
done

#REPO="${REPO-${PWD##*/}}"

echo "REPO: " $REPO "User: " $USER

curl -u $USER https://api.github.com/user/repos -d '{"name":"'$REPO'"}'
git remote add origin git@github.com:$USER/$REPO.git
git push origin master
